### ISSUE TITLE
[0.9.5.x] Release TODOs

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/w3-total-cache-fixed#196]
- [x] Rename-less installation instructions
- [x] Uploading proper ZIP-s, Rename-less installation instructions in release notes
- [ ] ~~Get update notifications and installs through the WP plugin page~~
- [ ] ~~update external library like [CSSTidy ](https://github.com/szepeviktor/w3-total-cache-fixed/tree/master/lib/CSSTidy) and [JSMin](https://github.com/szepeviktor/w3-total-cache-fixed/tree/master/lib/Minify)~~
- [ ] ~~implement new modern features like [dns prefetch](https://varvy.com/rel/dns-prefetch.html), [assets preload](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/)~~
- [ ] ~~clear `w3-total-cache-fixed` by removing all unnecessary code eg.: support, licensing, etc (now simply hidden)~~
- [ ] write a [wiki](https://github.com/szepeviktor/w3-total-cache-fixed/wiki) page on how w3tc works and how to set up correctly
- [ ] ~~implement my plugins in w3tc: [Speed Up - Lazy Load](https://wordpress.org/plugins/speed-up-lazy-load/); [Speed Up - Menu](https://wordpress.org/plugins/speed-up-menu/); [Speed Up - Translation](https://wordpress.org/plugins/speed-up-translation/)~~

_**Note:** some of the above are complete in v0.9.4.x so it'll be quick whip up for v0.9.5.x in due time_

**Comment by amiga-500** [comment]
Sure!  Will update this soon.

Curious @szepeviktor ... I just realized something:  Did you update Travis to reflect the rebranding too?

For example:

_travis-ci.org/szepeviktor/**fix-w3tc**.svg?branch=master_ 

is now

_travis-ci.org/szepeviktor/**w3-total-cache-fixed**.svg?branch=master_

Cheers
Kimberly :octocat:

**Comment by szepeviktor** [comment]
> Did you update Travis to reflect the rebranding too?

Just now.

**Comment by nigrosimone** [comment]
My proposals for next releases:

*moved to top

**Comment by amiga-500** [comment]
^wow nice proposal set and love your plugins.  I'll probably play around with new things after the new year.

**Comment by nigrosimone** [comment]
implementation of modern features assets preload https://github.com/szepeviktor/w3-total-cache-fixed/pull/224. need test

**Comment by szepeviktor** [comment]
I was about to update my official 0.9.5.1 but then I've realized....

**Comment by nolens** [comment]
> implement new modern features like dns prefetch, assets preload
> implement into w3tc my plugins: Speed Up - Lazy Load; Speed Up - Menu; Speed Up - Translation

It would be absolutely great to see those features implemented! 
 I am not a coder, but an **enthusiastic** user of your fork. Thanks for your excellent work so far.

**Comment by nigrosimone** [comment]
Good news: some days ago i have sent a mail to w3tc support with all issue we have fixed. Today i have got back a reply from the support that says that most has been applied or already fixed.

**Comment by szepeviktor** [comment]
After 0.9.5.1?

**Comment by szepeviktor** [comment]
It could be unpublished...
https://plugins.trac.wordpress.org/log/w3-total-cache/

**Comment by nigrosimone** [comment]
> After 0.9.5.1?

maybe... they wasn't told me when it will release the new version (or release something).

**Comment by nigrosimone** [comment]
After other email sended to w3tc support, they say: the next release is planned for next week.

At this point we have to talking about 0.9.5.x branch.

I have sends some e-mails for inform w3tc support with all issues we have fixed. w3tc support have checked all single commints. All issues we have discovered are fixed, with our solution or his "alternative" solution (they has shared it into the mail).

The w3tc support seems very disponible and respond very fast, this is a good news because it seems at works and the official plugin it's not abandoned (again).

My idea is keep the 0.9.5.x branch always synced with the last official release and incorporate fixes, improvements, and enhancements over the last official WordPress release. At each new official release, the 0.9.5.x branch must re-synced with wp version (even if we lose something). At each new our fixes, improvements, and enhancements we send a mail to w3tc support to inform it. The idea is build a collaboration between the projects.

**Comment by szepeviktor** [comment]
It feels very organic.

If you could - please add meaningful commit messages: cause + fix to ease w3tc support's reviews.

**Comment by nigrosimone** [comment]
> If you could - please add meaningful commit messages: cause + fix to ease w3tc support's reviews.

yes, i do! see latest pull requests, eg https://github.com/szepeviktor/w3-total-cache-fixed/pull/272

> It feels very organic.

without money feed :D
